# Generated by Django 6.0.4 on 2026-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0001_initial_squashed_0006_alter_event_event_revision_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
