# Generated by Django 6.0.4 on 2026-05-07 16:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0007_alter_phone_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='subject_prop_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='subject_prop_location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='subject_prop_location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
