# Generated by Django 6.0.4 on 2026-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0008_courtcase_subject_prop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='subject_prop_address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
