# Generated by Django 6.0.4 on 2026-05-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0009_courtcase_subject_prop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geocoding_accuracy',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='court_consolidated_display_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='subject_prop_hardcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='court_records.address'),
        ),
    ]
