# Generated by Django 6.0.4 on 2026-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0010_address_geocoding_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='actor_uri',
            field=models.URLField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='actor_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='case_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='dispositions_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='sentences_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='uri',
            field=models.URLField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='actors_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='charges_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='court_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='dispositions_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='events_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='minutes_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='payments_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='receivables_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='sentences_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='subject_prop_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='subject_prop_location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='uri',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courtpayment',
            name='court_payment_case_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtpayment',
            name='court_payment_payor_actor_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='courtpayment',
            name='court_payment_recipient_actor_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='charge_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='case_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='payor_actor_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='recipient_actor_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='charges_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
