# Generated by Django 6.0.4 on 2026-05-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0011_alter_actors_actor_uri_alter_charge_actor_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='actor_uri',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='uri',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
    ]
