# Generated by Django 6.0.4 on 2026-05-11 19:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0012_alter_actors_actor_uri_alter_court_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=254)),
                ('display_name', models.CharField(max_length=254)),
                ('identifier', models.CharField(max_length=254)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
