# Generated by Django 6.0.4 on 2026-05-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_records', '0013_overlaygeography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overlaygeography',
            options={'ordering': ['dataset_name', 'identifier'], 'verbose_name': 'Geography Overlay', 'verbose_name_plural': 'Geography Overlays'},
        ),
    ]
