#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
	CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
	CREATE DATABASE $DATABASE_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;
	GRANT ALL PRIVILEGES ON SCHEMA public TO $DATABASE_USERNAME;

EOSQL

psql -v ON_ERROR_STOP=1 --username $DATABASE_USERNAME --dbname $DATABASE_NAME <<-EOSQL
    CREATE EXTENSION postgis;
EOSQL

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
	CREATE USER $MB_DB_USER WITH PASSWORD '$MB_DB_PASS';
	CREATE DATABASE $MB_DB_DBNAME;
	GRANT ALL PRIVILEGES ON DATABASE $MB_DB_DBNAME TO $MB_DB_USER;
	GRANT ALL PRIVILEGES ON SCHEMA public TO $MB_DB_USER;

EOSQL
