#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
	CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
	CREATE DATABASE $DATABASE_NAME;
    CREATE EXTENSION postgis;
	GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;
EOSQL

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
	CREATE USER $MB_DB_USER WITH PASSWORD '$MB_DB_PASS';
	CREATE DATABASE $MB_DB_DBNAME;
	GRANT ALL PRIVILEGES ON DATABASE $MB_DB_DBNAME TO $MB_DB_USER;
EOSQL
